const assaultlist = document.getElementById('assault-list');
const arlist = `
<button class="gun w-100">Type 25</button>
<button class="gun w-100">M16</button>
<button class="gun w-100">AK117</button>
<button class="gun w-100">AK-47</button>
<button class="gun w-100">ASM10</button>
<button class="gun w-100">M4</button>
<button class="gun w-100">BK57</button>
<button class="gun w-100">LK24</button>
<button class="gun w-100">ICR-1</button>
<button class="gun w-100">Man-O-War</button>
<button class="gun w-100">KN-44</button>
<button class="gun w-100">HBRa3</button>
<button class="gun w-100">HVK-30</button>
<button class="gun w-100">DR-H</button>
<button class="gun w-100">Peacekeeper MK2</button>
<button class="gun w-100">FR .556</button>
<button class="gun w-100">AS VAL</button>
<button class="gun w-100">CR-56 AMAX</button>
<button class="gun w-100">M13</button>
<button class="gun w-100">Swordfish</button>
<button class="gun w-100">Kilo 141</button>
<button class="gun w-100">Oden</button>
<button class="gun w-100">Krig 6</button>
<button class="gun w-100">EM2</button>
<button class="gun w-100">Maddox</button>
<button class="gun w-100">FFAR 1</button>
<button class="gun w-100">Grau 5.56</button>
<button class="gun w-100">Groza</button>
<button class="gun w-100">Type 19</button>
<button class="gun w-100">BP50</button>
<button class="gun w-100">LAG 53</button>
<button class="gun w-100">XM4</button>
<button class="gun w-100">Vargo-S</button>
`; assaultlist.innerHTML = arlist;