const assaultlist = document.getElementById('assault-list');
const arlist = `
<div class="row gap-2 d-flex justify-content-center">
<button class="btn btn-dark col col-sm-12 col-lg-4">Type 25</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">M16</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">AK117</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">AK-47</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">ASM10</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">M4</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">BK57</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">LK24</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">ICR-1</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">Man-O-War</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">KN-44</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">HBRa3</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">HVK-30</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">DR-H</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">Peacekeeper MK2</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">FR .556</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">AS VAL</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">CR-56 AMAX</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">M13</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">Swordfish</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">Kilo 141</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">Oden</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">Krig 6</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">EM2</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">Maddox</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">FFAR 1</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">grau 5.56</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">Groza</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">Type 19</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">BP50</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">LAG 53</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">XM4</button>
<button class="btn btn-dark col col-sm-12 col-lg-4">Vargo-S</button>
</div>
`; assaultlist.innerHTML = arlist;