const sniperlist = document.getElementById('sniper-list');
const srlist = `
<button class="gun w-100">XPR-50</button>
<button class="gun w-100">Arctic.50</button>
<button class="gun w-100">M21 EBR</button>
<button class="gun w-100">DL Q33</button>
<button class="gun w-100">Locus</button>
<button class="gun w-100">NA-45</button>
<button class="gun w-100">Outlaw</button>
<button class="gun w-100">Rytex AMR</button>
<button class="gun w-100">SVD</button>
<button class="gun w-100">koshka</button>
<button class="gun w-100">ZRG 20mm</button>
<button class="gun w-100">HDR</button>
<button class="gun w-100">LW3-Tundra</button>
<button class="gun w-100">3-Line Rifle</button>
`; sniperlist.innerHTML = srlist;